### ISSUE TITLE
[ Difficulty: Beginner ] Update Favicon and Tab Text

### ISSUE THREAD

**Issue by sheldonej** [soundscape-community/authoring-tool#21]
**Description**
1. The favicon is currently a broken image. This needs to be replaced with the Soundscape Community Logo.
2. The text in the tab next to the favicon says "Soundscape Author" this needs to be converted to "Authoring Tool"

**To Reproduce**
1. Start the application on your device
2. See the error in the tab of your browser.

**Expected behavior**
The favicon should be the soundscape community logo and the text next to it in the tab should be "Authoring Tool"

**Comment by typicaladrian** [comment]
Changes were made to index.html to reflect what was needed for this issue.
